services:
  database:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  python:
    build:
      dockerfile: Dockerfile.python-dev
    volumes:
      - ${PWD}:${PWD}:delegated
    working_dir: ${PWD}
    command: ${COMPOSE_COMMAND:-bash}

volumes:
  postgres-data:
