services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    ports:
      - "3000:3000"
      - "5000:5000"

  database:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

volumes:
  postgres-data:
