version: '3.8'

services:

  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  # node_dev:
  #   extends:
  #     file: docker-compose.yml
  #     service: node
  #   ports:
  #     - "3000:3000"
  #   env_file: .env.dev

  # node:
  #   image: node:16
  #   user: app
  #   volumes:
  #     - /workspaces/example-api-grpc:/app
  #   command: ${COMPOSE_COMMAND:-bash}

  # python:
  #   build:
  #     context: .
  #     dockerfile: api.dev.Dockerfile 
  #   user: app
  #   volumes:
  #     - ./workspaces/example-api-grpc:/app
  #     - ./Makefile:/opt/app/Makefile:ro
  #   command: ${COMPOSE_COMMAND:-bash}

volumes:
  postgres-data:
